const dataExport = {
  // 行人
  person: [
    { label: '参与方编号', name: 'personparticipantId' },
    { label: '案例编号', name: 'participant_personcaseNumber' },
    { label: '性别', name: 'participant_number_person' },
    { label: '人员伤亡情况', name: 'type_of_participant_person' },
    { label: '高度（身高）', name: 'agePerson' },
    { label: '参与方颜色（衣着颜色）', name: 'genderPerson' },
    { label: '黑暗处或夜间衣物可见性', name: 'vehHight' },
    { label: '事故发生地点', name: 'weight_person' },
    { label: '行人穿越机动车道位置', name: 'participantColorPerson' },
    {
      label: '行人行走方向',
      name: 'visibilityInTheDarkOrAtNight',
    },
    { label: '行人运动状态', name: 'main_accident_cause_person' },
    { label: '行人速度（km/h）', name: 'accidentLocation' },
    {
      label: '行人被撞部位',
      name: 'pedestrianCrossingTheMotorwayLocation',
    },
    { label: '碰撞前行人相对于车辆的位置', name: 'pedestrianWalkingDirection' },
    { label: '穿越机动车道时能否被看到', name: 'pedestrianMovement' },
    { label: '是否因为视野盲区造成事故', name: 'pedestrian_speed' },
    { label: '是否由停靠车辆造成行人的视野盲区', name: 'pedestrian_being_hit' },
    {
      label: '是否有其他造成行人视线盲区的物体',
      name: 'positionOfPedestrianRelativeToVehicleBeforeCollision',
    },
    {
      label: '开始反应到碰撞前是否有应急姿态',
      name: 'can_you_be_seen_when_crossing_the_motorway',
    },
    {
      label: '行人是否从障碍物后穿出',
      name: 'whether_it_is_caused_by_a_blind_spot_of_vision',
    },
    {
      label: '行人意识到危险之前是否加速',
      name: 'whetherBlindareaOfPedestrianIsCausedByParkedVehicle',
    },
    {
      label: '事故前行人行走方向是否改变',
      name: 'areThereOtherObjectsThatCausePedestrianBlindSpots',
    }
  ],
  // 二轮车
  twoWheel: [
    { label: '参与方编号', name: 'twoWheelparticipantsId' },
    { label: '案例编号', name: 'twoWheelCaseNumber' },
    { label: '车辆具体类型', name: 'participant_number_twoWheel' },
    { label: '参与方颜色', name: 'typeOfParticipantTwoWheel' },
    { label: '长度', name: 'veh_length_two_wheel' },
    { label: '宽度', name: 'veh_width_two_wheel' },
    { label: '高度', name: 'veh_hight_two_wheel' },
    { label: '二/三轮车载重', name: 'weight_two_wheel' },
    { label: '主要过错1', name: 'coeff_frict_two_wheel' },
    { label: '主要过错2', name: 'wheelbase_two_wheel' },
    { label: '二轮车运动方向', name: 'seat_height_from_the_ground' },
    { label: '二轮车速度（km/h）', name: 'electric_vehicle_or_not' },
    { label: '二轮车第一碰撞位置相对自身方位', name: 'main_accident_cause_two_wheel' },
    { label: '骑车人性别', name: 'twoWheelerMovementDirection' },
    { label: '衣着颜色', name: 'twoWheelSpeed' },
    { label: '骑车人伤亡情况', name: 'light_switched_on' },
    {
      label: '是否佩戴头盔',
      name:
        'orientation_of_first_collision_position_of_two_wheeled_vehicle',
    },
    { label: '头盔颜色', name: 'age_two_wheel' },
    { label: '在黑暗处或夜间衣物可见性', name: 'Clothingvisibilityindarkplacesnight' },
    { label: '事故时转向避让反应', name: 'genderTwoWheel' },
    { label: '事故时二轮车转向灯是否开启', name: 'clothing_color' },
    { label: '是否有优先权', name: 'wearHelmet' },
    { label: '开始反应到碰撞前是否采取转向措施', name: 'helmet_color' },
    {
      label: '事故发生前车辆运动类型',
      name: 'conspicuousness_of_clothing_in_the_dark',
    },
    {
      label: '二轮车乘客数',
      name: 'relation_of_driving_direction',
    },
    { label: '乘员伤亡情况', name: 'steering_reaction_in_accident' }
  ],
  // 车
  car: [
    { label: '案例编号', name: 'carCaseNumber' },
    { label: '参与方编号', name: 'participantNumber_car' },
    { label: '车辆类型', name: 'type_of_participant_car' },
    { label: '是否有EDR报告', name: 'participant_color_car' },
    { label: '车辆品牌', name: 'veh_length' },
    { label: 'VIM', name: 'veh_width' },
    { label: '车辆顺坏情况', name: 'veh_hight' },
    { label: '车辆人员伤亡情况', name: 'weight_car' },
    { label: '参与方颜色', name: 'occ_front' },
    { label: '长度(mm)', name: 'occ_rear' },
    { label: '宽度(mm)', name: 'roof_cargo' },
    { label: '高度(mm)', name: 'trunk_cargo' },
    { label: '轴距', name: 'cog_height' },
    { label: '前轮距(mm)', name: 'cog_axle' },
    { label: '后轮距(mm)', name: 'veh_frontoverhang' },
    { label: '主要过错1', name: 'veh_shape_h3' },
    { label: '主要过错2', name: 'wheelbase' },
    { label: '是否有优先权', name: 'trackwidth_1' },
    { label: '所在道路方向', name: 'trackwidth_2' },
    { label: '事故前车辆要避撞的对向', name: 'tire_model' },
    { label: '事故前车辆的避撞行为', name: 'tire_pressure' },
    { label: '是否有视野盲区（车外）', name: 'coeff_frict' },
    { label: '车辆初始速度', name: 'moment_roll_l' },
    { label: '碰撞时速度', name: 'moment_pitch_l' },
    { label: '事故发生前车辆运动类型', name: 'moment_yaw_l' },
    { label: '开始反应到碰撞前是否采取转向措施', name: 'cruise_control' },
    { label: '制动执行机构类型', name: 'adaptive_cruise_acc' },
    { label: '是否使用安全带', name: 'seat_belt_reminder' },
    {
      label: '安全气囊是否展开',
      name: 'whether_there_is_active_pedestrian_protection_device',
    },
    { label: '是否有行人主动保护装置', name: 'type_of_power_steering' },
    { label: '是否有ABS防抱死系统', name: 'type_of_brake_actuator' },
    {
      label: '是否有EBD制动力分配系统系统',
      name: 'ebd_braking_force_distribution_system',
    },
    { label: '是否有ESP/VSC车身电子稳定系统', name: 'abs_anti_lock_system' },
    {
      label: '是否有ASR/TCS/TRC/ATC牵引力控制系统',
      name: 'esp_vsc_body_stabilization_system',
    },
    {
      label: '是否有EBA/BAS刹车辅助系统',
      name: 'asr_tcs_trc_atc_traction_control_system',
    },
    { label: '胎压监测装置', name: 'eba_bas_brake_assistant_system' },
    { label: '并线辅助/盲点监测', name: 'tire_pressure_monitoring_device' },
    {
      label: '车道偏离预警LDW',
      name: 'concurrent_auxiliary_or_blind_spot_monitoring',
    },
    { label: '车道保持系统LKA', name: 'lane_departure_warning_ldw' },
    { label: '自动紧急制动系统（AEB）', name: 'lane_keeping_system_lka' },
    { label: '预碰撞安全系统AWS', name: 'automatic_emergency_braking' }
  ],
  // 道路信息
  road: [
    { label: '案例编号', name: 'roadCaseNumber' },
    { label: '参与方编号', name: 'participantNumber' },
    { label: '参与方所在道路名称', name: 'nameofroadparticipantlocated' },
    { label: '总体机动车道数（条）', name: 'totalnumberofmotorvehicle' },
    { label: '参与方行驶方向机动车道数（条）', name: 'directionRoadAtCollisionPoint' },
    { label: '参与方行驶方向对向机动车道数', name: 'administrativeRankOfRoad' },
    { label: '非机动车道', name: 'classOfRoad' },
    { label: '道路横截面的轮廓', name: 'typeOfCityRoad' },
    { label: '对向机动车道隔离形式', name: 'totalNumberOfMotorVehicleLanes' },
    { label: '本侧机非车道隔离形式', name: 'numberVehicleLanesOnEastSide' },
    { label: '对向机动车道侧机非车道隔离形式', name: 'numberVehicleLanesOnWestSide' },
    { label: '道路总宽度', name: 'numberVehicleLanesOnSouthSide' },
    { label: '所在车道的宽度', name: 'numberVehicleLanesOnNorthSide' },
    { label: '高允许车速', name: 'nonMotorVehicleLaneOfEastWest' },
    { label: '现场有何种交通警告标志', name: 'nonMotorVehicleLaneOfSouthNorth' },
    { label: '现场有何种交通禁令标志', name: 'nonMotorVehiclthNorth' },
    { label: '道路的线形', name: 'outlineOfRoadCrossSection' },
    { label: '沿道路方向的趋势', name: 'trafficSignsNotVisible' },
    { label: '路面材料', name: 'intersectionSignalLamp' },
    {
      label: '道路表面污染',
      name: 'isolationFormOfOppositeVehicleLane',
    },
    {
      label: '路表潮湿度',
      name: 'isolation_form_of_east_no_motor_vehicle_lane',
    },
    {
      label: '路面状况',
      name: 'isolation_form_of_west_no_motor_vehicle_lane',
    },
    {
      label: '交通标志是否被阻挡不可见',
      name: 'isolation_form_of_motor_vehicle_lane',
    },
    {
      label: '路口信号灯',
      name: 'isolation_form_of_sourth_no_motor_vehicle_lane',
    },
    {
      label: '路灯是否开启',
      name: 'isolation_form_of_north_no_motor_vehicle_lane',
    },
    { label: '路灯的密度', name: 'overall_width_of_road' },
    { label: '是否有轨道', name: 'the_linear_shape_of_the_road' },
    { label: '影响视线的障碍物', name: 'radius_of_curve' },
    { label: '道路状况评估', name: 'trendsAlongTheRoad' },
    { label: '是否有建筑设施', name: 'slope_of_the_trend' },
    { label: '交通限速设施', name: 'maximumAllowedSpeed' },
    { label: '车辆是否冲到相应路边', name: 'traffic_warning_sign' },
    { label: '是否为变宽路段', name: 'traffic_ban_sign' },
    { label: '是否有为变窄路段', name: 'street_lighting' },
    { label: '是否有隧道', name: 'density_of_street_lighting' },
    { label: '是否为匝道口', name: 'type_of_road_surface' },
  ],
  // 环境信息
  env: [
    { label: '案例编号', name: 'envCaseNumber' },
    { label: '路段信息', name: 'Roadsectioninformation' },
    { label: '天气', name: 'weather' },
    { label: '事故具体时间', name: 'accidentspecifictime' },
    { label: '日间太阳光线', name: 'daytimeSunRays' },
    { label: '雾天能见度', name: 'visibilityinfog' },
    { label: '摄氏温度', name: 'temperature' },
    { label: '照明情况', name: 'lightingSituation' },
  ],
  // 总体信息
  total: [
    {label: '案例编号', name: 'totalCaseNumber'},
    {label: '委托号', name: 'commissionNumber'},
    {label: '参与方总数', name: 'participantsNum'},
    {label: '事故形态', name: 'accidentForm'},
    {label: '事故分类', name: 'accidentType'},
    {label: '障碍物类型', name: 'obstacleType'},
    {label: '视频类型', name: 'videoType'},
    {label: '参与方一视角下参与方二的走向', name: 'thedirectionofparticipant2'},
    {label: '经度-东经（度）', name: 'eastlongitude'},
    {label: '纬度-北纬（度）', name: 'northlatitude'},
    {label: '事故关注点', name: 'incidentFocus'},
  ],
}
export default dataExport